download only made default, use -e to also extract

diff --git a/aurdownload b/aurdownload
--- a/aurdownload
+++ b/aurdownload
@@ -7,32 +7,30 @@
 #          http://www.gnu.org/licenses/gpl.txt
 
 if [ -z "$*" ]; then
-  echo "aurdownload - download and extract packages from AUR"
+  echo "aurdownload - download and optionally extract packages from AUR"
   echo "Error: You must specify package name(s)"
-  echo
-  echo "Use --nodelete option for preserving old source code, but remember"
-  echo "it must be on the first place right after aurdownload commmand!"
   exit 1
 fi
-
+EXTRACT=0
 for name in "$@"; do
-  echo "Removing old archive '$name.tar.gz'..."
-  rm -f "$name.tar.gz"
-
-
-  echo "Downloading package '$name'..."
-  nameprefix=`echo $name|cut -c1-2`
-  wget -nv "http://aur.archlinux.org/packages/$nameprefix/$name/$name.tar.gz"
-  if [ $? -ne 0 ]; then
-    echo "Can't download '$name.tar.gz'. Skipping this package..."
-    echo
-    continue
-  fi
-
-  echo "Extracting '$name.tar.gz' archive..."
-  tar -xvzpf "$name.tar.gz"
-  echo
-
-  echo "Deleting $name.tar.gz"
-  rm "$name.tar.gz"
+    if  [ $name == "-e" ]; then
+	    EXTRACT=1
+	    shift
+    else
+	echo "Removing old archive '$name.tar.gz'..."
+	rm -f "$name.tar.gz"
+	
+	echo "Downloading package '$name'..."
+	nameprefix=`echo $name|cut -c1-2`
+	wget -nv "http://aur.archlinux.org/packages/$nameprefix/$name/$name.tar.gz"
+	if [ $? -ne 0 ]; then
+	    echo "Can't download '$name.tar.gz'. Skipping this package..."
+	    echo 
+	    continue
+	fi
+	if [ $EXTRACT = 1 ]; then
+	    tar -xvzpf "$name.tar.gz" && rm "$name.tar.gz"
+	fi
+    fi
 done
+
